#!/bin/sh

# mkdist - make a distribution of the CQL-Java software
# $Id: mkdist,v 1.4 2007-06-06 14:39:11 mike Exp $

version=`cat VERSION`
distdir=cql-java-$version
distfile=$distdir.tar.gz
tmpdir=/tmp/$distdir
echo "Building $distdir"
trap "rm -rf $tmpdir" 1 2 15	# 0
cp -rp . $tmpdir
cd $tmpdir
find . \( -name CVS -o -name .cvsignore \) -print | xargs rm -rf
rm mkdist etc/chris-hubick etc/xslt
( cd src/org/z3950/zing/cql && make && make clean )
( cd docs && make )
( cd test/regression && make distclean )
cd ..
tar cf - $distdir | gzip -9v > $distfile
rm -rf $tmpdir
echo "Made $distfile"
